name: kbm_admin
description: KBM administrative console (Super Admin, Admin Cliente, Operador, Auditor).
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  fl_chart: ^1.2.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/kbm_logo.png
    - assets/images/card_black_template.png
